### ISSUE TITLE
Alias creation throws error

### ISSUE THREAD

**Issue by Lipnevich** [wavesplatform/waves-api#71] opened 2018-07-22 08:59 UTC
In time of creation alias in Google Functions (Node v6.14.0) with data:

const createAliasData = {
  alias: 'AirDropSmartRewarderBot',
  fee: 100000,
  timestamp: Date.now()
};
Waves.API.Node.transactions.broadcast(Waves.constants.CREATE_ALIAS_TX_NAME, createAliasData,
        wallet.keyPair).then((alias) => console.log(alias));

Error appears: 
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
    at Object.oldBrowser (/user_code/node_modules/@waves/waves-api/dist/waves-api.min.js:1:547277)
    at nodeRandom (/user_code/node_modules/@waves/waves-api/dist/waves-api.min.js:1:65661)
    at secureRandom (/user_code/node_modules/@waves/waves-api/dist/waves-api.min.js:1:66655)
    at Object.randomUint8Array (/user_code/node_modules/@waves/waves-api/dist/waves-api.min.js:1:66886)
    at Object.buildTransactionSignature (/user_code/node_modules/@waves/waves-api/dist/waves-api.min.js:1:86883)
    at getBytes.then.dataBytes (/user_code/node_modules/@waves/waves-api/dist/waves-api.min.js:1:77976)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by xenohunter** [comment] 2018-07-30 12:17
Thank you for reporting, the issue is with the build process, we'll fix that soon.

**Comment by xenohunter** [comment] 2018-07-30 12:18
Closed as a duplicate of https://github.com/wavesplatform/waves-api/issues/69.

**Closed by xenohunter** 2018-07-30 12:18 UTC
