### ISSUE TITLE
Secure random number generation is not supported by this browser

### ISSUE THREAD

**Issue by unknownfix** [wavesplatform/waves-api#72] opened 2018-07-22 11:18 UTC
Nodejs version 8
Waves api version 1.3.0
For Waves api version 1.1.0 works fine

`Waves.Seed.create() `

`Secure random number generation is not supported by this browser. Use Chrome, Firefox or Internet Explorer 11
Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11
    at Object.oldBrowser (/Users/unknownfix/Documents/My/Projects/monoreto-chain/node_modules/@waves/waves-api/dist/waves-api.min.js:1:547277)
    at nodeRandom`

@xenohunter please fix asap

**Comment by xenohunter** [comment] 2018-07-30 12:18
Thanks for reporting, we're working on it.

**Comment by xenohunter** [comment] 2018-07-30 12:18
Closed as a duplicate of https://github.com/wavesplatform/waves-api/issues/69.

**Closed by xenohunter** 2018-07-30 12:18 UTC
